### ISSUE TITLE
Check for players in deletion zone

### ISSUE THREAD

**Issue by thebgpikester** [victorcotap/BTI#1]
I didn't read all the code, but a note, if this is the same Zeus used by some of my peers, they used a deletion command (destroy)and it picked up a player client.

Between DCS 1.5 and now Destroy() has changed. It didn't used to do anything. However it seems to have reverted to the bug post 1.5 where the players representation to others will freeze or disappear to other players and get ignored by AI. it effectively makes them a Ninja.

If you aren't, please filter out client units. If you are then someone made a similar code called Zeus that didn't.

**Comment by victorcotap** [comment]
Hi @thebgpikester!

I'm not sure which code you reference here. This repo houses (wrongly) two different missions, BTI and PTI (Zeus).

I use `Destroy()` in PTI only on units that have been previously spanwed by Zeus and that I keep track off in a table
```
function SUPPORTWipeSpawnedAssets()
    for i = 1, #ZeusSpawnedAssets do
        local spawnedGroup = ZeusSpawnedAssets[i]
        spawnedGroup:Destroy(false)
        ZeusSpawnedAssets[i] = nil
    end
end

function SUPPORTWipeLastAsset()
    local spawnedGroup = ZeusSpawnedAssets[#ZeusSpawnedAssets]
    spawnedGroup:Destroy(false)
    ZeusSpawnedAssets[#ZeusSpawnedAssets] = nil
end
```

In BTI and PTI I also use a `-destroy` or `-exfill` that lets the game commander destroy units if needed but the zone used to scan for units is so small, unless someone is flying at 800ft right in that 800ft dome, it shouldn't take any client into its detection zone (unless done at an airbase I guess).

I'm not sure who is using this Zeus but maybe you can direct them here if they have questions and if they are. I'll try to add a filter when I get a chance
